### PR TITLE
Configured environment variables in frontend

### PR DESCRIPTION
**Pull request by Debajyoti111**
**Issue Number**
ISSUE #17 
fixes #1 
Added support for environment variables in the front end using `react-dotenv` and updated .gitignore to include `.env` file. Also added `BACKEND_URL` as an environment variable and whitelisted the environment variables in `package.json`

**Describe the changes you've made**

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

Preview: Deploy preview link here with the appropriate route
[modified package.json](https://github.com/Debajyoti111/Talk-Line/blob/addEnv/frontend/package.json)
[modified .gitignore](https://github.com/Debajyoti111/Talk-Line/blob/addEnv/frontend/.gitignore)
[added .env.example](https://github.com/Debajyoti111/Talk-Line/blob/addEnv/frontend/.env.example)
[modified CONTRIBUTING.md](https://github.com/Debajyoti111/Talk-Line/blob/addEnv/CONTRIBUTING.md)

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by Debajyoti111** [comment]
Please check if the changes made are correct.

**Comment by kailash360** [comment]
The implementation look fine. Can you change the variable name to `REACT_APP_BACKEND_URL` ?

It is a requirement according to https://create-react-app.dev/docs/adding-custom-environment-variables.

**Comment by kailash360** [comment]
Also create a `.env.example` file for reference, and write the instruction to add environment variables in frontend during setup, n the documentation.

**Comment by Debajyoti111** [comment]
Sure, working on it!

**Comment by Debajyoti111** [comment]
I have updated the code as well as the documentation accordingly, please check.

**Comment by kailash360** [comment]
Great work @Debajyoti111

**Pull request merged**
