### PR TITLE
Added lock files in .gitignore 

### PR DESCRIPTION
**Pull request by Aaroh1**
**Issue Number**
issue#11
Added package-lock.json files in .gitignore in both backend as well as frontend folders.

fixes #1
-->issue#11
Added package-lock.json files in .gitignore in both backend as well as frontend folders.

**Describe the changes you've made**

Added package-lock.json files in .gitignore in both backend as well as frontend folders so as to remove them from the repo and untrack changes made on these files.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deploy preview link here with the appropriate route

https://github.com/kailash360/Talk-Line/blob/main/frontend/.gitignore
https://github.com/kailash360/Talk-Line/blob/main/backend/.gitignore

Screenshot 2022-10-03 152109

### CODE REVIEW

**Comment by kailash360** [comment]
@Aaroh-1 
Can you please squash the commits into a single one?

**Comment by Aaroh1** [comment]
@kailash360 
Sure! Working on it.

**Comment by Aaroh1** [comment]
@kailash360 
I've squashed the 3 commits into a single self-descriptive one. Please check.

**Comment by kailash360** [comment]
@Aaroh-1 
Please resolve the conflicts

**Comment by Aaroh1** [comment]
> @Aaroh-1 Please resolve the conflicts

Done!

**Comment by Aaroh1** [comment]
Hey @kailash360! Could you please verify the PR?

**Pull request merged**
